export const WORDS = {
  login: "ログイン",
  email: "メールアドレス",
  password: "パスワード",
  forgotPassword: "パスワードを忘れた場合",
  others: "または",
  loginButton: "ログイン",
  googleLogin: "Googleでログイン",
  dashboard: "Dashboard",
  employees: "Employees",
  assets: "Assets",
  tasks: "Tasks",
  settings: "設定",
  logout: "ログアウト",
};
