export const WORDS = {
  login: "ログイン",
  email: "メールアドレス",
  password: "パスワード",
  forgotPassword: "パスワードを忘れた場合",
  others: "または",
  loginButton: "ログイン",
  googleLogin: "Googleでログイン",
  dashboard: "Dashboard",
  employees: "Employees",
  assets: "Assets",
  tasks: "Tasks",
  settings: "設定",
  logout: "ログアウト",
  dashboardDescription: "人事管理システム全体の現況",
  totalNumberOfEmployees: "総従業員数",
  recentEvents: "最近のイベント",
  ongoingTasks: "進行中のタスク",
  delayedTasks: "遅延タスク",
  emergencyTasks: "緊急タスク",
  contractExpirationAlerts: "契約満了アラート",
};
